package com.aubb.server.modules.identityaccess.infrastructure.user;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import java.util.Collection;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface UserMapper extends BaseMapper<UserEntity> {

    @Select({
        "<script>",
        "SELECT COUNT(*)",
        "FROM users u",
        "LEFT JOIN academic_profiles ap ON ap.user_id = u.id",
        "WHERE 1 = 1",
        "<if test='orgUnitId != null'>",
        "  AND u.primary_org_unit_id = #{orgUnitId}",
        "</if>",
        "<if test='orgUnitId == null'>",
        "  AND (",
        "    <if test='manageableOrgIds != null and manageableOrgIds.size() > 0'>",
        "      u.primary_org_unit_id IN",
        "      <foreach collection='manageableOrgIds' item='managedOrgId' open='(' separator=',' close=')'>",
        "        #{managedOrgId}",
        "      </foreach>",
        "    </if>",
        "    <if test='includeUsersWithoutOrg'>",
        "      <if test='manageableOrgIds != null and manageableOrgIds.size() > 0'> OR </if>",
        "      u.primary_org_unit_id IS NULL",
        "    </if>",
        "  )",
        "</if>",
        "<if test='accountStatus != null'>",
        "  AND u.account_status = #{accountStatus}",
        "</if>",
        "<if test='keyword != null and keyword != \"\"'>",
        "  AND (",
        "    lower(u.username) LIKE CONCAT('%', #{keyword}, '%')",
        "    OR lower(u.display_name) LIKE CONCAT('%', #{keyword}, '%')",
        "    OR lower(u.email) LIKE CONCAT('%', #{keyword}, '%')",
        "    OR lower(COALESCE(ap.real_name, '')) LIKE CONCAT('%', #{keyword}, '%')",
        "    OR lower(COALESCE(ap.academic_id, '')) LIKE CONCAT('%', #{keyword}, '%')",
        "  )",
        "</if>",
        "<if test='academicId != null and academicId != \"\"'>",
        "  AND lower(COALESCE(ap.academic_id, '')) LIKE CONCAT('%', #{academicId}, '%')",
        "</if>",
        "<if test='identityType != null'>",
        "  AND ap.identity_type = #{identityType}",
        "</if>",
        "<if test='roleCode != null'>",
        "  AND EXISTS (",
        "    SELECT 1",
        "    FROM user_scope_roles usr",
        "    WHERE usr.user_id = u.id",
        "      AND usr.role_code = #{roleCode}",
        "  )",
        "</if>",
        "</script>"
    })
    long countVisibleUsers(
            @Param("manageableOrgIds") Collection<Long> manageableOrgIds,
            @Param("includeUsersWithoutOrg") boolean includeUsersWithoutOrg,
            @Param("keyword") String keyword,
            @Param("academicId") String academicId,
            @Param("identityType") String identityType,
            @Param("accountStatus") String accountStatus,
            @Param("roleCode") String roleCode,
            @Param("orgUnitId") Long orgUnitId);

    @Select({
        "<script>",
        "SELECT u.*",
        "FROM users u",
        "LEFT JOIN academic_profiles ap ON ap.user_id = u.id",
        "WHERE 1 = 1",
        "<if test='orgUnitId != null'>",
        "  AND u.primary_org_unit_id = #{orgUnitId}",
        "</if>",
        "<if test='orgUnitId == null'>",
        "  AND (",
        "    <if test='manageableOrgIds != null and manageableOrgIds.size() > 0'>",
        "      u.primary_org_unit_id IN",
        "      <foreach collection='manageableOrgIds' item='managedOrgId' open='(' separator=',' close=')'>",
        "        #{managedOrgId}",
        "      </foreach>",
        "    </if>",
        "    <if test='includeUsersWithoutOrg'>",
        "      <if test='manageableOrgIds != null and manageableOrgIds.size() > 0'> OR </if>",
        "      u.primary_org_unit_id IS NULL",
        "    </if>",
        "  )",
        "</if>",
        "<if test='accountStatus != null'>",
        "  AND u.account_status = #{accountStatus}",
        "</if>",
        "<if test='keyword != null and keyword != \"\"'>",
        "  AND (",
        "    lower(u.username) LIKE CONCAT('%', #{keyword}, '%')",
        "    OR lower(u.display_name) LIKE CONCAT('%', #{keyword}, '%')",
        "    OR lower(u.email) LIKE CONCAT('%', #{keyword}, '%')",
        "    OR lower(COALESCE(ap.real_name, '')) LIKE CONCAT('%', #{keyword}, '%')",
        "    OR lower(COALESCE(ap.academic_id, '')) LIKE CONCAT('%', #{keyword}, '%')",
        "  )",
        "</if>",
        "<if test='academicId != null and academicId != \"\"'>",
        "  AND lower(COALESCE(ap.academic_id, '')) LIKE CONCAT('%', #{academicId}, '%')",
        "</if>",
        "<if test='identityType != null'>",
        "  AND ap.identity_type = #{identityType}",
        "</if>",
        "<if test='roleCode != null'>",
        "  AND EXISTS (",
        "    SELECT 1",
        "    FROM user_scope_roles usr",
        "    WHERE usr.user_id = u.id",
        "      AND usr.role_code = #{roleCode}",
        "  )",
        "</if>",
        "ORDER BY u.created_at DESC, u.id DESC",
        "LIMIT #{limit} OFFSET #{offset}",
        "</script>"
    })
    List<UserEntity> selectVisibleUsersPage(
            @Param("manageableOrgIds") Collection<Long> manageableOrgIds,
            @Param("includeUsersWithoutOrg") boolean includeUsersWithoutOrg,
            @Param("keyword") String keyword,
            @Param("academicId") String academicId,
            @Param("identityType") String identityType,
            @Param("accountStatus") String accountStatus,
            @Param("roleCode") String roleCode,
            @Param("orgUnitId") Long orgUnitId,
            @Param("offset") long offset,
            @Param("limit") long limit);
}
