package com.aubb.server.modules.audit.domain;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    PLATFORM_CONFIG_UPDATED,
    USER_CREATED,
    USER_IMPORTED,
    USER_STATUS_CHANGED,
    USER_IDENTITIES_CHANGED,
    USER_PROFILE_UPDATED,
    USER_MEMBERSHIPS_CHANGED,
    ORG_UNIT_CREATED,
    ACADEMIC_TERM_CREATED,
    COURSE_CATALOG_CREATED,
    COURSE_OFFERING_CREATED,
    TEACHING_CLASS_CREATED,
    TEACHING_CLASS_FEATURES_UPDATED,
    COURSE_MEMBERS_BATCH_ADDED,
    COURSE_MEMBERS_IMPORTED,
    ASSIGNMENT_CREATED,
    ASSIGNMENT_PUBLISHED,
    ASSIGNMENT_CLOSED,
    SUBMISSION_ARTIFACT_UPLOADED,
    SUBMISSION_CREATED,
    JUDGE_JOB_ENQUEUED
}
