package com.aubb.server.modules.notification.domain;

public enum NotificationType {
    COURSE_ANNOUNCEMENT_PUBLISHED,
    COURSE_RESOURCE_PUBLISHED,
    ASSIGNMENT_PUBLISHED,
    JUDGE_COMPLETED,
    ASSIGNMENT_GRADES_PUBLISHED,
    GRADE_APPEAL_RESOLVED,
    LAB_PUBLISHED,
    LAB_REPORT_SUBMITTED,
    LAB_REPORT_PUBLISHED
}
