CREATE TABLE auth_permission_defs (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL CHECK (length(name) <= 128),
    domain TEXT NOT NULL CHECK (length(domain) <= 64),
    description TEXT NOT NULL CHECK (length(description) <= 256),
    sensitive BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE auth_group_templates (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE CHECK (length(code) <= 64),
    name TEXT NOT NULL CHECK (length(name) <= 128),
    scope_type TEXT NOT NULL CHECK (scope_type IN ('SCHOOL', 'COLLEGE', 'COURSE', 'OFFERING', 'CLASS')),
    system_managed BOOLEAN NOT NULL DEFAULT FALSE,
    built_in BOOLEAN NOT NULL DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE auth_group_template_permissions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES auth_group_templates (id) ON DELETE CASCADE,
    permission_code TEXT NOT NULL REFERENCES auth_permission_defs (code) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_auth_group_template_permissions_template_permission
    ON auth_group_template_permissions (template_id, permission_code);
CREATE INDEX ix_auth_group_template_permissions_permission
    ON auth_group_template_permissions (permission_code);

CREATE TABLE auth_groups (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES auth_group_templates (id) ON DELETE RESTRICT,
    scope_type TEXT NOT NULL CHECK (scope_type IN ('SCHOOL', 'COLLEGE', 'COURSE', 'OFFERING', 'CLASS')),
    scope_ref_id BIGINT NOT NULL,
    display_name TEXT NOT NULL CHECK (length(display_name) <= 128),
    managed_by_system BOOLEAN NOT NULL DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_auth_groups_template_scope
    ON auth_groups (template_id, scope_type, scope_ref_id);
CREATE INDEX ix_auth_groups_scope
    ON auth_groups (scope_type, scope_ref_id);

CREATE TABLE auth_group_members (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES auth_groups (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    source_type TEXT NOT NULL CHECK (source_type IN ('SYSTEM_SYNC', 'MANUAL', 'IMPORT')),
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_auth_group_members_group_user
    ON auth_group_members (group_id, user_id);
CREATE INDEX ix_auth_group_members_user_id
    ON auth_group_members (user_id);

INSERT INTO auth_permission_defs (code, name, domain, description, sensitive) VALUES
    ('org.unit.read', '读取组织节点', 'organization', '查看组织树与组织节点详情', FALSE),
    ('org.unit.manage', '管理组织节点', 'organization', '创建、修改或停用组织节点', FALSE),
    ('user.read', '读取用户', 'user', '查看用户与用户目录信息', FALSE),
    ('user.manage', '管理用户', 'user', '创建、修改和停用用户', FALSE),
    ('user.identity.manage', '管理治理身份', 'user', '分配或撤销治理身份', TRUE),
    ('user.membership.manage', '管理成员关系', 'user', '维护组织成员关系', FALSE),
    ('user.session.revoke', '失效用户会话', 'user', '强制失效指定用户会话', TRUE),
    ('course.read', '读取课程', 'course', '查看课程信息', FALSE),
    ('course.manage', '管理课程', 'course', '创建与维护课程配置', FALSE),
    ('offering.read', '读取开课实体', 'course', '查看开课实体信息', FALSE),
    ('offering.manage', '管理开课实体', 'course', '创建与维护开课实体配置', FALSE),
    ('class.read', '读取教学班', 'course', '查看教学班信息', FALSE),
    ('class.manage', '管理教学班', 'course', '创建与维护教学班配置', FALSE),
    ('member.read', '读取成员列表', 'course', '查看课程或教学班成员列表', FALSE),
    ('member.manage', '管理成员列表', 'course', '添加、移除或调整成员', FALSE),
    ('assignment.read', '读取作业', 'assignment', '查看作业内容', FALSE),
    ('assignment.create', '创建作业', 'assignment', '创建作业草稿', FALSE),
    ('assignment.update', '更新作业', 'assignment', '编辑作业内容', FALSE),
    ('assignment.publish', '发布作业', 'assignment', '发布作业', FALSE),
    ('assignment.close', '关闭作业', 'assignment', '关闭作业', FALSE),
    ('question.read', '读取题目', 'assignment', '查看题库题目', FALSE),
    ('question.manage', '管理题目', 'assignment', '创建、编辑和归档题目', FALSE),
    ('judge.profile.manage', '管理评测环境', 'judge', '维护评测环境模板与配置', TRUE),
    ('judge.hidden.read', '读取隐藏评测资产', 'judge', '查看隐藏测试、SPJ 与评测脚本', TRUE),
    ('judge.hidden.manage', '管理隐藏评测资产', 'judge', '维护隐藏测试、SPJ 与评测脚本', TRUE),
    ('submission.read.own', '读取本人提交', 'submission', '查看本人提交及附件', FALSE),
    ('submission.read.class', '读取班级提交', 'submission', '查看班级范围提交', TRUE),
    ('submission.read.offering', '读取开课提交', 'submission', '查看开课实体范围提交', TRUE),
    ('submission.code.read_sensitive', '读取敏感代码内容', 'submission', '查看源码、编译日志和敏感详情', TRUE),
    ('submission.grade', '批改提交', 'submission', '对提交进行人工批改或复核', TRUE),
    ('submission.rejudge', '重判提交', 'submission', '触发提交重判', TRUE),
    ('grade.read.own', '读取本人成绩', 'grading', '查看本人成绩册与成绩详情', FALSE),
    ('grade.read.unpublished', '读取未发布成绩', 'grading', '查看教师已保存但未发布成绩', TRUE),
    ('grade.export.class', '导出班级成绩', 'grading', '导出教学班成绩册', TRUE),
    ('grade.export.offering', '导出开课成绩', 'grading', '导出开课实体成绩册', TRUE),
    ('grade.override', '覆盖成绩', 'grading', '覆盖自动评测或已评成绩', TRUE),
    ('grade.publish', '发布成绩', 'grading', '发布成绩快照与通知', TRUE),
    ('appeal.read.own', '读取本人申诉', 'grading', '查看本人成绩申诉', FALSE),
    ('appeal.read.class', '读取班级申诉', 'grading', '查看班级范围成绩申诉', TRUE),
    ('appeal.review', '处理申诉', 'grading', '复核并处理成绩申诉', TRUE),
    ('lab.read', '读取实验', 'lab', '查看实验与实验报告', FALSE),
    ('lab.manage', '管理实验', 'lab', '创建、发布和关闭实验', FALSE),
    ('lab.report.review', '评审实验报告', 'lab', '评审和发布实验报告', TRUE),
    ('audit.read', '读取审计日志', 'audit', '查看审计日志', TRUE),
    ('audit.source.read', '读取审计源码', 'audit', '出于审计目的读取敏感源码内容', TRUE),
    ('auth.group.manage', '管理授权组', 'authz', '创建、修改和维护授权组', TRUE),
    ('auth.explain.read', '读取授权解释', 'authz', '查看某次授权判定解释', TRUE);

INSERT INTO auth_group_templates (code, name, scope_type, system_managed, built_in, status) VALUES
    ('school-admin', '学校管理员', 'SCHOOL', TRUE, TRUE, 'ACTIVE'),
    ('college-admin', '学院管理员', 'COLLEGE', TRUE, TRUE, 'ACTIVE'),
    ('course-admin', '课程管理员', 'COURSE', TRUE, TRUE, 'ACTIVE'),
    ('class-admin', '班级管理员', 'CLASS', TRUE, TRUE, 'ACTIVE'),
    ('offering-instructor', '开课教师', 'OFFERING', TRUE, TRUE, 'ACTIVE'),
    ('class-instructor', '班级教师', 'CLASS', TRUE, TRUE, 'ACTIVE'),
    ('offering-ta', '开课助教', 'OFFERING', TRUE, TRUE, 'ACTIVE'),
    ('class-ta', '班级助教', 'CLASS', TRUE, TRUE, 'ACTIVE'),
    ('student', '学生', 'CLASS', TRUE, TRUE, 'ACTIVE'),
    ('observer', '观察者', 'OFFERING', TRUE, TRUE, 'ACTIVE'),
    ('audit-readonly', '审计只读组', 'SCHOOL', FALSE, TRUE, 'ACTIVE'),
    ('grade-corrector', '成绩纠错组', 'OFFERING', FALSE, TRUE, 'ACTIVE');

INSERT INTO auth_group_template_permissions (template_id, permission_code)
SELECT template.id, bindings.permission_code
FROM (
    VALUES
        ('school-admin', 'org.unit.read'),
        ('school-admin', 'org.unit.manage'),
        ('school-admin', 'user.read'),
        ('school-admin', 'user.manage'),
        ('school-admin', 'user.identity.manage'),
        ('school-admin', 'user.membership.manage'),
        ('school-admin', 'user.session.revoke'),
        ('school-admin', 'course.read'),
        ('school-admin', 'course.manage'),
        ('school-admin', 'offering.read'),
        ('school-admin', 'offering.manage'),
        ('school-admin', 'class.read'),
        ('school-admin', 'class.manage'),
        ('school-admin', 'member.read'),
        ('school-admin', 'member.manage'),
        ('school-admin', 'audit.read'),
        ('school-admin', 'audit.source.read'),
        ('school-admin', 'auth.group.manage'),
        ('school-admin', 'auth.explain.read'),
        ('college-admin', 'org.unit.read'),
        ('college-admin', 'user.read'),
        ('college-admin', 'user.manage'),
        ('college-admin', 'user.membership.manage'),
        ('college-admin', 'user.session.revoke'),
        ('college-admin', 'course.read'),
        ('college-admin', 'course.manage'),
        ('college-admin', 'offering.read'),
        ('college-admin', 'offering.manage'),
        ('college-admin', 'class.read'),
        ('college-admin', 'class.manage'),
        ('college-admin', 'member.read'),
        ('college-admin', 'member.manage'),
        ('course-admin', 'course.read'),
        ('course-admin', 'course.manage'),
        ('course-admin', 'offering.read'),
        ('course-admin', 'offering.manage'),
        ('course-admin', 'class.read'),
        ('course-admin', 'class.manage'),
        ('course-admin', 'member.read'),
        ('course-admin', 'member.manage'),
        ('class-admin', 'class.read'),
        ('class-admin', 'class.manage'),
        ('class-admin', 'user.read'),
        ('class-admin', 'user.manage'),
        ('class-admin', 'user.membership.manage'),
        ('class-admin', 'user.session.revoke'),
        ('class-admin', 'member.read'),
        ('class-admin', 'member.manage'),
        ('offering-instructor', 'offering.read'),
        ('offering-instructor', 'offering.manage'),
        ('offering-instructor', 'class.read'),
        ('offering-instructor', 'class.manage'),
        ('offering-instructor', 'member.read'),
        ('offering-instructor', 'member.manage'),
        ('offering-instructor', 'assignment.read'),
        ('offering-instructor', 'assignment.create'),
        ('offering-instructor', 'assignment.update'),
        ('offering-instructor', 'assignment.publish'),
        ('offering-instructor', 'assignment.close'),
        ('offering-instructor', 'question.read'),
        ('offering-instructor', 'question.manage'),
        ('offering-instructor', 'judge.profile.manage'),
        ('offering-instructor', 'submission.read.offering'),
        ('offering-instructor', 'submission.code.read_sensitive'),
        ('offering-instructor', 'submission.grade'),
        ('offering-instructor', 'submission.rejudge'),
        ('offering-instructor', 'grade.export.offering'),
        ('offering-instructor', 'grade.override'),
        ('offering-instructor', 'grade.publish'),
        ('offering-instructor', 'appeal.read.class'),
        ('offering-instructor', 'appeal.review'),
        ('offering-instructor', 'lab.read'),
        ('offering-instructor', 'lab.manage'),
        ('offering-instructor', 'lab.report.review'),
        ('class-instructor', 'class.read'),
        ('class-instructor', 'member.read'),
        ('class-instructor', 'assignment.read'),
        ('class-instructor', 'assignment.create'),
        ('class-instructor', 'assignment.update'),
        ('class-instructor', 'assignment.publish'),
        ('class-instructor', 'assignment.close'),
        ('class-instructor', 'submission.read.class'),
        ('class-instructor', 'submission.code.read_sensitive'),
        ('class-instructor', 'submission.grade'),
        ('class-instructor', 'grade.export.class'),
        ('class-instructor', 'grade.override'),
        ('class-instructor', 'appeal.read.class'),
        ('class-instructor', 'appeal.review'),
        ('class-instructor', 'lab.read'),
        ('class-instructor', 'lab.manage'),
        ('class-instructor', 'lab.report.review'),
        ('offering-ta', 'offering.read'),
        ('offering-ta', 'class.read'),
        ('offering-ta', 'member.read'),
        ('offering-ta', 'assignment.read'),
        ('offering-ta', 'submission.read.offering'),
        ('offering-ta', 'submission.code.read_sensitive'),
        ('offering-ta', 'submission.grade'),
        ('offering-ta', 'grade.export.offering'),
        ('offering-ta', 'appeal.read.class'),
        ('offering-ta', 'lab.read'),
        ('offering-ta', 'lab.report.review'),
        ('class-ta', 'class.read'),
        ('class-ta', 'member.read'),
        ('class-ta', 'assignment.read'),
        ('class-ta', 'submission.read.class'),
        ('class-ta', 'submission.code.read_sensitive'),
        ('class-ta', 'submission.grade'),
        ('class-ta', 'grade.export.class'),
        ('class-ta', 'appeal.read.class'),
        ('class-ta', 'lab.read'),
        ('class-ta', 'lab.report.review'),
        ('student', 'class.read'),
        ('student', 'assignment.read'),
        ('student', 'submission.read.own'),
        ('student', 'grade.read.own'),
        ('student', 'appeal.read.own'),
        ('student', 'lab.read'),
        ('observer', 'offering.read'),
        ('observer', 'class.read'),
        ('observer', 'assignment.read'),
        ('audit-readonly', 'audit.read'),
        ('audit-readonly', 'audit.source.read'),
        ('audit-readonly', 'auth.explain.read'),
        ('grade-corrector', 'submission.read.offering'),
        ('grade-corrector', 'submission.code.read_sensitive'),
        ('grade-corrector', 'grade.override'),
        ('grade-corrector', 'appeal.review')
) AS bindings(template_code, permission_code)
JOIN auth_group_templates template ON template.code = bindings.template_code;
